//
// Created by remy on 11-09-20.
//

#ifndef C_OOKIECLIKER_COOKIESPERSECONDACHIEVEMENT_H
#define C_OOKIECLIKER_COOKIESPERSECONDACHIEVEMENT_H



class CookiesPerSecondAchievement {

};



#endif //C_OOKIECLIKER_COOKIESPERSECONDACHIEVEMENT_H
